/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MediaPlayer */

#ifndef _Included_MediaPlayer
#define _Included_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef MediaPlayer_FOCUS_TRAVERSABLE_UNKNOWN
#define MediaPlayer_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef MediaPlayer_FOCUS_TRAVERSABLE_DEFAULT
#define MediaPlayer_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef MediaPlayer_FOCUS_TRAVERSABLE_SET
#define MediaPlayer_FOCUS_TRAVERSABLE_SET 2L
#undef MediaPlayer_TOP_ALIGNMENT
#define MediaPlayer_TOP_ALIGNMENT 0.0f
#undef MediaPlayer_CENTER_ALIGNMENT
#define MediaPlayer_CENTER_ALIGNMENT 0.5f
#undef MediaPlayer_BOTTOM_ALIGNMENT
#define MediaPlayer_BOTTOM_ALIGNMENT 1.0f
#undef MediaPlayer_LEFT_ALIGNMENT
#define MediaPlayer_LEFT_ALIGNMENT 0.0f
#undef MediaPlayer_RIGHT_ALIGNMENT
#define MediaPlayer_RIGHT_ALIGNMENT 1.0f
#undef MediaPlayer_serialVersionUID
#define MediaPlayer_serialVersionUID -7644114512714619750LL
#undef MediaPlayer_serialVersionUID
#define MediaPlayer_serialVersionUID 4613797578919906343LL
#undef MediaPlayer_INCLUDE_SELF
#define MediaPlayer_INCLUDE_SELF 1L
#undef MediaPlayer_SEARCH_HEAVYWEIGHTS
#define MediaPlayer_SEARCH_HEAVYWEIGHTS 1L
#undef MediaPlayer_NOT_OBSCURED
#define MediaPlayer_NOT_OBSCURED 0L
#undef MediaPlayer_PARTIALLY_OBSCURED
#define MediaPlayer_PARTIALLY_OBSCURED 1L
#undef MediaPlayer_COMPLETELY_OBSCURED
#define MediaPlayer_COMPLETELY_OBSCURED 2L
#undef MediaPlayer_WHEN_FOCUSED
#define MediaPlayer_WHEN_FOCUSED 0L
#undef MediaPlayer_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define MediaPlayer_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef MediaPlayer_WHEN_IN_FOCUSED_WINDOW
#define MediaPlayer_WHEN_IN_FOCUSED_WINDOW 2L
#undef MediaPlayer_UNDEFINED_CONDITION
#define MediaPlayer_UNDEFINED_CONDITION -1L
#undef MediaPlayer_IS_DOUBLE_BUFFERED
#define MediaPlayer_IS_DOUBLE_BUFFERED 0L
#undef MediaPlayer_ANCESTOR_USING_BUFFER
#define MediaPlayer_ANCESTOR_USING_BUFFER 1L
#undef MediaPlayer_IS_PAINTING_TILE
#define MediaPlayer_IS_PAINTING_TILE 2L
#undef MediaPlayer_IS_OPAQUE
#define MediaPlayer_IS_OPAQUE 3L
#undef MediaPlayer_KEY_EVENTS_ENABLED
#define MediaPlayer_KEY_EVENTS_ENABLED 4L
#undef MediaPlayer_FOCUS_INPUTMAP_CREATED
#define MediaPlayer_FOCUS_INPUTMAP_CREATED 5L
#undef MediaPlayer_ANCESTOR_INPUTMAP_CREATED
#define MediaPlayer_ANCESTOR_INPUTMAP_CREATED 6L
#undef MediaPlayer_WIF_INPUTMAP_CREATED
#define MediaPlayer_WIF_INPUTMAP_CREATED 7L
#undef MediaPlayer_ACTIONMAP_CREATED
#define MediaPlayer_ACTIONMAP_CREATED 8L
#undef MediaPlayer_CREATED_DOUBLE_BUFFER
#define MediaPlayer_CREATED_DOUBLE_BUFFER 9L
#undef MediaPlayer_IS_PRINTING
#define MediaPlayer_IS_PRINTING 11L
#undef MediaPlayer_IS_PRINTING_ALL
#define MediaPlayer_IS_PRINTING_ALL 12L
#undef MediaPlayer_IS_REPAINTING
#define MediaPlayer_IS_REPAINTING 13L
#undef MediaPlayer_WRITE_OBJ_COUNTER_FIRST
#define MediaPlayer_WRITE_OBJ_COUNTER_FIRST 14L
#undef MediaPlayer_RESERVED_1
#define MediaPlayer_RESERVED_1 15L
#undef MediaPlayer_RESERVED_2
#define MediaPlayer_RESERVED_2 16L
#undef MediaPlayer_RESERVED_3
#define MediaPlayer_RESERVED_3 17L
#undef MediaPlayer_RESERVED_4
#define MediaPlayer_RESERVED_4 18L
#undef MediaPlayer_RESERVED_5
#define MediaPlayer_RESERVED_5 19L
#undef MediaPlayer_RESERVED_6
#define MediaPlayer_RESERVED_6 20L
#undef MediaPlayer_WRITE_OBJ_COUNTER_LAST
#define MediaPlayer_WRITE_OBJ_COUNTER_LAST 21L
#undef MediaPlayer_REQUEST_FOCUS_DISABLED
#define MediaPlayer_REQUEST_FOCUS_DISABLED 22L
#undef MediaPlayer_INHERITS_POPUP_MENU
#define MediaPlayer_INHERITS_POPUP_MENU 23L
#undef MediaPlayer_OPAQUE_SET
#define MediaPlayer_OPAQUE_SET 24L
#undef MediaPlayer_AUTOSCROLLS_SET
#define MediaPlayer_AUTOSCROLLS_SET 25L
#undef MediaPlayer_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define MediaPlayer_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef MediaPlayer_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define MediaPlayer_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     MediaPlayer
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MediaPlayer_init
  (JNIEnv *, jobject);

/*
 * Class:     MediaPlayer
 * Method:    exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MediaPlayer_exit
  (JNIEnv *, jobject);

/*
 * Class:     MediaPlayer
 * Method:    open
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_MediaPlayer_open
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     MediaPlayer
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MediaPlayer_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     MediaPlayer
 * Method:    getwidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MediaPlayer_getwidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     MediaPlayer
 * Method:    getheight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MediaPlayer_getheight
  (JNIEnv *, jobject, jint);

/*
 * Class:     MediaPlayer
 * Method:    getframe
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_MediaPlayer_getframe
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
